### ISSUE TITLE
Does not re-analyze 

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#66] opened 2024-03-13 07:10 UTC
**Describe the bug**
When I analyzed a large amounts of audio (700+ hours), the analysis was often not completed. Therefore, I would like to re-run the audio analysis with v1.5.1.

**To Reproduce**
1. Open all files that have already been analyzed before (here f.e. 720*1 hour long files).
2. Click on 'Analyze all Open Files' or 'Re-analyse all Open Files'.
3. It won't analyze them, instead, it switches to the archive. 
4. There's no error.

**Expected behavior**
It should re-analyze all files.

**Screenshots**
![Screenshot 2024-03-13 at 07 59 49](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/dfe71e4e-ffbd-4387-8f85-4ad5f75c7e72)

![Screenshot 2024-03-13 at 08 00 27](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/42901c42-525b-4b98-8add-c8ee6e1af4dc)

**Additional context**
Mac, v1.5.1. It's a minor issue, I could just remove the archive file. What's important to me is that it now actually finishes analysis completely.

**Comment by Mattk70** [comment] 2024-03-13 10:45
There's a typo in one of my variables preventing the re-analyse functinos from working. This will be fixed in the 1.6.0 release, also hopefully, the issue with analyses not completing. What I have found is that the stream reading the file occasionally sends a packet of one byte at the file's end. When this happens, Chirpity can't construct an audio file from the packet, because the wav format is in two byte chunks.  Consequently, one fewer predictions are received than expected and the analysis for that file never completes. I have a workaround for this which fixes this issue where I have seen it.

**Closed by Mattk70** 2024-03-13 10:45 UTC

**Comment by Mattk70** [comment] 2024-03-14 09:49
Hey,

Notifications, so far as I know, persist until you dismiss them. If analysis wasn't completing (as was a problem in previous versions), the notification wouldn't be triggered. 1.6.0 should have fixed this, so for last night's analysis you should have had a notification waiting after it had completed.

I checked the logs, and it would appear that your analysis completed without issue. No errors were logged, anyway. 

What I did notice was that it has reported the analysis duration as 2,570,071 seconds, which is 713.9 hours.

There could be a discrepancy for a number of reasons.  The first and most obvious is that *all* your files aren't exactly 1 hour long. Could you check this? The quick way to check, since I assume they are WAV flles all recorded with the same settings - are they all the same file size? Use spotlight to search for waveform audio in the top level folder of your files, view as a list and make sure the size column is visible.

Let me know? If there are exactly 720 files all the same file size, I'll start exploring other reasons

2. The Red-Throated Pipit. Did you note the file it was in or save this detection?

Sadly, I'm not going to be able to reproduce an issue that only appears when you open 700 * 1 hour wav filtes.  So let's try to get to a minimal case where the issue can be replicated. *If* the latest version of Chirpity is skipping sections of files, it (almost certainly) will skip that section in the same file whenever it's processed. Let's try to find one of those files.

3. Save locations. A similar thing - I can't do this with 700+ files. It's highly unlikely this issue is related to the file types/ length anyway. I did it with three 3 hour long m4a files and again with 1084 short (< 1 minute) wav files. In both cases the location was available in the archive location dropdown after following the process you described. 

I did find another issue, which is that the location you've set doesn't immediately appear if you select amend file recording location again on the currently open file after setting update all locations. I suspect this is because the updated metadata for the current file metadata isn't refreshed in the UI after changing this setting. If you pick another from the file list accessed on the open files dropdown it has the correct location, If you reselect the first file, the location has been updated and is correct.

**Comment by Vollpflock** [comment] 2024-03-14 11:13
Oh wow sorry, didn't want you to have so much work. I'll look more into it and get back. 

Short note: Correct, not all of them are 1 hour long. Now I found the notification. Unfortunately, I don't know where the Red-Throated Pipit was in my recordings.  However, I'll try to figure it out by analyzing small batches.

**Comment by Vollpflock** [comment] 2024-04-13 10:51
2. Unfortunately,  I still haven't located the Red-throated Pipit. It's a shame, this would have been a great species. Meanwhile, I think it's actually possible that it was initially categorized as a different species (e.g., tree pipit), and that I found it afterwards. Sorry for the hassle.
