### ISSUE TITLE
Analysis stops before ready

### ISSUE THREAD

**Issue by HansNorelius** [Mattk70/Chirpity-Electron#121] opened 2024-04-24 07:55 UTC
The analysis of a night recording session, 10 hours, it rather often stops before finished. 

It can stop after diferent length, e.g. 70% or 99%. If it finishes it normally takes about 10 minutes.

It don´t leave any reason. I can stop the analysis at this locked stage and use whats ready. This morning I analysed the same file 4 times but it never finished.

I use Threads 8 and Batch Size 32.

Best Regards, Hasse

**Comment by Mattk70** [comment] 2024-04-24 16:22
Hello Hesse, thanks for letting me know. I think I know why this happens but cannot replicate the issue on my computer. I have attempted to address it with changes made in version 1.8.0. If you'd like to try that version - please let me know if the issue is fixed?

**Comment by Mattk70** [comment] 2024-04-24 20:33
There may still be an issue on the Mac version - are you using a Mac? If so, I have a pre-release which I *think* has squashed this bug: https://github.com/Mattk70/Chirpity-Electron/releases/tag/v1.8.1.

**Comment by HansNorelius** [comment] 2024-04-25 04:17
I,m on Windows 11 and just tried the 1.8.0 version. It seems to work very well, and fast! Thanks Matt!

**Comment by Mattk70** [comment] 2024-04-25 10:01
Awesome, that really good to hear! I'll go ahead and close this issue

**Closed by Mattk70** 2024-04-25 10:01 UTC
