### ISSUE TITLE
Freezing After Exporting a Record

### ISSUE THREAD

**Issue by Vollpflock** [Mattk70/Chirpity-Electron#50] opened 2024-02-17 08:31 UTC
**Describe the bug**
I encountered an issue where the system freezes after exporting a record. I attempted this with more than 820 files, each 1 hour long, amounting to around 142,000 recognitions in total. This might be causing it. Otherwise, everything else seemed to work fine (there was no lag, and I was able to save and edit records without issue). 

**Expected behavior**
It should not freeze.

**Screenshots**
![Screenshot 2024-02-17 at 08 38 16](https://github.com/Mattk70/Chirpity-Electron/assets/26574621/ca6a66b2-1dbf-4903-bc0a-35a34a2a78bc)

**Additional context**
Version 1.1.0
Mac

**Comment by Mattk70** [comment] 2024-02-17 14:47
Hmm. I'm not sure what's going on here. The error shown is because there is no active row in the table, and there should always be an active row. I can fix that error, but I'm not sure this will address the underlying cause. Are there any errors showing in the other 'worker' window?

**Comment by Vollpflock** [comment] 2024-02-17 15:29
Thanks, Matt. Well, I forgot to look at it. Thought I could easily quit the app to make it work. Will reanalyze the files this night and check again.

**Comment by Mattk70** [comment] 2024-02-17 17:39
I figued out what the problem is. When you page to the next screen, the active row is cleared. If you create a manual record on that screen - it errors. I can prevent the error, but it will then return you to the beginning of the file. I need to figure out how to bring you back to the point in the file where you just created the record.

**Comment by Vollpflock** [comment] 2024-02-17 18:51
You're smart. I already forgot that I created a manual record.

**Comment by Mattk70** [comment] 2024-02-23 23:02
As I suspect the freeze was related to the earlier error around creating a manual record, which is fixed in 1.2.0 - I'm going to close this. Let me know if you still have the "freeze on export" problem.

**Closed** 2024-02-23 23:02 UTC
