### ISSUE TITLE
Chirpity nocmig

### ISSUE THREAD

**Issue by Patrick5956** [Mattk70/Chirpity-Electron#155] opened 2024-10-19 15:14 UTC
Chirpity doesn't work after the last update.

![image](https://github.com/user-attachments/assets/be3cdfc5-77e0-4cbd-a573-06dae15f8166)

**Comment by Vollpflock** [comment] 2024-10-19 17:26
That’s as precise a bug report as it gets xD

**Comment by Patrick5956** [comment] 2024-10-20 18:32
This is what I get when I want to open a file.Op 20 okt 2024 om 10:51 heeft Mattk70 ***@***.***> het volgende geschreven:﻿
It works for me, and others. Do you think you could set out some details of your issue - per the template? Thanks

**Comment by Mattk70** [comment] 2024-10-21 00:08
I'm pretty sure the email reply hasn't worked, your message has been garbled. Could you try again on the gitHub site?
https://github.com/Mattk70/Chirpity-Electron/issues/155

Thanks

**Comment by Mattk70** [comment] 2024-10-22 08:16
> Chirpity doesn't work after the last update.
> 
> ![image](https://private-user-images.githubusercontent.com/185619940/378533589-be3cdfc5-77e0-4cbd-a573-06dae15f8166.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NTIxMzAsIm5iZiI6MTcyOTU1MTgzMCwicGF0aCI6Ii8xODU2MTk5NDAvMzc4NTMzNTg5LWJlM2NkZmM1LTc3ZTAtNGNiZC1hNTczLTA2ZGFlMTVmODE2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyMVQyMzAzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZmIyMzdlNzlkNjUxNjc5NWE0YzJhYzVjYjBjYmFjZmI5ZjAyMGJiMzRiM2QyNjQyOGY0MmI2NWRkZjJjNjU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tiYncjcWJMyh7vlo5qThK5ArLCt5C24oC8RFNfGSxvU)

OK. A couple of suggestions to try for version 2.1.2. When you open the app,  before opening any file go to 'help > show tour'. Do you get the same error or does an audio file with a Redwing in it open? 
If you get the error, try resetting your settings to their defaults (bottom link in settings) and restart the app. Does the tour start and open the Redwing file now?

**Comment by Patrick5956** [comment] 2024-10-23 18:21
Hello,

 

Now I get constantly  “ERROR: output stream closed” after I analysed a file.

 

Van: Mattk70 ***@***.***> 
Verzonden: dinsdag 22 oktober 2024 10:17
Aan: Mattk70/Chirpity-Electron ***@***.***>
CC: Patrick5956 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Mattk70/Chirpity-Electron] Chirpity nocmig (Issue #155)

 

Chirpity doesn't work after the last update.



OK. A couple of suggestions to try for version 2.1.2. When you open the app, before opening any file go to 'help > show tour'. Do you get the same error or does an audio file with a Redwing in it open?
If you get the error, try resetting your settings to their defaults (bottom link in settings) and restart the app. Does the tour start and open the Redwing file now?

**Comment by Mattk70** [comment] 2024-10-24 12:18
One specific file? Every file? To help you I need to be able to reproduce the problem. 

As you are unable to give the information requested in the template and prefer to give vague reports, I will close this issue because I cannot reproduce it.

**Closed by Mattk70** 2024-10-24 12:18 UTC
